AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 30
Metrics/ParameterLists:
  Max: 15
  MaxOptionalParameters: 5
Metrics/BlockNesting:
  Max: 5
