csv_headers: true
reverse_order: true
default_currency: $
fields:
  date: !!proc Date.strptime(row['Date'], '%m/%d/%Y')
  amount: !!proc >
    withdrawal, deposit = row[3..4].collect {|a| a.to_commodity unless a.empty?};
    ( deposit ? deposit.invert! : withdrawal ).quantity_as_s
  description: !!proc row['Description']
