client_id: "841596637004-vcljkfs9o45s12nq6g3r54vtu6htp8b9.apps.googleusercontent.com"
project_id: "ruby-rake-accounting"
client_secret: "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"
token_path: "google-token.yml"
application_name: "rvgp"
